# This is a basic workflow to help you get started with Actions

name: Build Artifacts

on:
  push:
    branches:
    - "**"
  pull_request:
    branches:
    - "**"

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Lint
        run: |
          go get -u golang.org/x/lint/golint
          golint ./...
      - name: Test
        run: go test -v ./...
        
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build image
        id: docker_build
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY_LAB: quizdeck/lab
          ECR_REPOSITORY_ROUTER_DISCORD: quizdeck/router_discord
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_LAB:$IMAGE_TAG -f ./lab/Dockerfile .
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_ROUTER_DISCORD:$IMAGE_TAG -f ./router_discord/Dockerfile .

      - name: Push to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY_LAB: quizdeck/lab
          ECR_REPOSITORY_ROUTER_DISCORD: quizdeck/router_discord
          IMAGE_TAG: latest
        if: github.ref == 'refs/heads/project/**' && github.event_name == 'pull_request'
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_LAB:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_ROUTER_DISCORD:$IMAGE_TAG

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

