name: 'Terraform'

on:
  push:
    branches:
    - "**"
  pull_request:
    branches:
    - "**"

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: staging_environment
    env:
      TF_VAR_AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TERRAFORM_API_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: echo $PWD && echo $TF_VAR_AWS_ACCOUNT_ID && terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
      run: terraform apply -auto-approve
